### ISSUE TITLE
Show the 404 when I want to use the address to create the new page

### ISSUE THREAD

**Issue by tlytg456** [livechat/octopus#9]
Hello,

Thanks for your project.

I have met some problem after I deployed the program. I use nginx and the IP address to access the page, but when I want to create a new page via address, the page always go to the 404 not found page, But when I click the " Diagrams Help " link in index page, the web would router correctly.

Can you help me please?

Best,
Troy

**Comment by bolchowka** [comment]
Hello Troy,
it does not work for you because Octopus does not come with nginx config for SPA applications.

To run Octopus on nginx, you need to convert [.htaccess file](https://github.com/livechat/octopus/blob/master/.htaccess) from this repo to its nginx counterpart. [The tutorial on nginx page](https://www.nginx.com/blog/converting-apache-to-nginx-rewrite-rules/) should help you with that.

**Comment by tlytg456** [comment]
@bolchowka Hello bolchowka,
Actually, I do some config in the nginx and rewrite the url, and it works. following are the config:
```
location /{
     index index.html;
     if (-e $request_filename) {
         break;
     }
     if (!-e $request_filename) {
         rewrite ^/(.*)$ /index.html break;
         break;
     }
  }
```
Thanks for your reply
